using Content.Client._Arcane.RemoteImages;
using Content.Shared._Arcane.RemoteImages;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Arcane.DetailExaminable;

[GenerateTypedNameReferences]
public sealed partial class CharacterImageEditor : Control
{
    [Dependency] private IEntityManager _entityManager = default!;

    private OwnedTexture? _texture;
    private int _requestId;
    private bool _suppressUrlChanged;

    public event Action<string>? OnUrlChanged;

    public CharacterImageEditor()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        UrlInput.OnTextChanged += args => HandleUrlChanged(args.Text);
        UrlInput.OnTextEntered += _ => RequestPreview();
        PreviewButton.OnPressed += _ => RequestPreview();
        ClearButton.OnPressed += _ => UrlInput.Text = string.Empty;
    }

    public void SetUrl(string imageUrl)
    {
        _suppressUrlChanged = true;
        UrlInput.Text = imageUrl;
        _suppressUrlChanged = false;

        HandleUrlChanged(imageUrl, notify: false);
        if (!string.IsNullOrEmpty(imageUrl))
            RequestPreview();
    }

    private void HandleUrlChanged(string imageUrl, bool notify = true)
    {
        if (_suppressUrlChanged)
            return;

        ReleasePreview();

        if (string.IsNullOrWhiteSpace(imageUrl))
        {
            StatusLabel.Text = Loc.GetString("arcane-character-image-editor-empty");
            PreviewButton.Disabled = true;
            if (notify)
                OnUrlChanged?.Invoke(string.Empty);
            return;
        }

        if (!RemoteImageConstants.TryNormalizeImgboxPngUrl(imageUrl, out var normalized))
        {
            StatusLabel.Text = Loc.GetString("arcane-character-image-invalid-url");
            PreviewButton.Disabled = true;
            if (notify)
                OnUrlChanged?.Invoke(string.Empty);
            return;
        }

        StatusLabel.Text = Loc.GetString("arcane-character-image-editor-ready");
        PreviewButton.Disabled = false;
        if (notify)
            OnUrlChanged?.Invoke(normalized);
    }

    private void RequestPreview()
    {
        if (!RemoteImageConstants.TryNormalizeImgboxPngUrl(UrlInput.Text, out var normalized)
            || string.IsNullOrEmpty(normalized))
        {
            StatusLabel.Text = Loc.GetString("arcane-character-image-invalid-url");
            return;
        }

        ReleasePreview();
        StatusLabel.Text = Loc.GetString("arcane-character-image-loading");
        PreviewButton.Disabled = true;

        _requestId = _entityManager.System<RemoteImageSystem>().RequestImage(
            normalized,
            (texture, _) =>
            {
                _requestId = 0;
                _texture = texture;
                ImagePreview.Texture = texture;
                PreviewButton.Disabled = false;
                StatusLabel.Text = Loc.GetString(
                    "arcane-character-image-loaded",
                    ("width", texture.Width),
                    ("height", texture.Height));
            },
            error =>
            {
                _requestId = 0;
                PreviewButton.Disabled = false;
                StatusLabel.Text = error;
            });
    }

    private void ReleasePreview()
    {
        var requestId = _requestId;
        _requestId = 0;
        if (requestId != 0
            && _entityManager.TrySystem<RemoteImageSystem>(out var remoteImageSystem))
        {
            remoteImageSystem.CancelRequest(requestId);
        }

        ImagePreview.Texture = null;
        _texture?.Dispose();
        _texture = null;
    }

    protected override void ExitedTree()
    {
        ReleasePreview();
        base.ExitedTree();
    }
}
