using Content.Client.UserInterface.Controls;
using Content.Client._Arcane.RemoteImages;
using Content.Shared._Arcane.DetailExaminable;
using Content.Shared._Starlight.Character.Info;
using Content.Shared._Starlight.Character.Info.Components;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.IdentityManagement;
using Content.Shared.Mind;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Arcane.DetailExaminable;

[GenerateTypedNameReferences]
public sealed partial class DetailExaminableWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;

    private static readonly Direction[] RotationSequence =
    [
        Direction.East,
        Direction.North,
        Direction.West,
        Direction.South,
    ];

    private int _currentDirectionIndex = 3;
    private OwnedTexture? _characterImageTexture;
    private int _characterImageRequestId;

    public DetailExaminableWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PreviewTabs.SetTabTitle(0, Loc.GetString("arcane-detail-examinable-tab-appearance"));
        PreviewTabs.SetTabTitle(1, Loc.GetString("arcane-detail-examinable-tab-character"));
        PreviewTabs.SetTabTitle(2, Loc.GetString("arcane-detail-examinable-tab-hidden"));

        RotateLeftButton.OnPressed += _ => RotateDirection(-1);
        RotateRightButton.OnPressed += _ => RotateDirection(1);
        OnClose += ClearCharacter;
    }

    public void SetCharacter(EntityUid? target, IEntityManager entityManager, EntityUid viewer)
    {
        if (!target.HasValue)
        {
            ClearCharacter();
            return;
        }

        var entity = target.Value;
        var mind = entityManager.System<SharedMindSystem>().GetMind(entity);

        PreviewNameText.Text = Identity.Name(entity, entityManager, viewer);

        if (entityManager.TryGetComponent(entity, out HumanoidAppearanceComponent? humanoid))
        {
            var species = !string.IsNullOrWhiteSpace(humanoid.CustomSpecieName)
                ? humanoid.CustomSpecieName
                : _prototypeManager.TryIndex(humanoid.Species, out SpeciesPrototype? speciesPrototype)
                    ? Loc.GetString(speciesPrototype.Name)
                    : humanoid.Species.Id;
            var sex = Loc.GetString($"humanoid-profile-editor-sex-{humanoid.Sex.ToString().ToLowerInvariant()}-text");
            var gender = Loc.GetString($"humanoid-profile-editor-pronouns-{humanoid.Gender.ToString().ToLowerInvariant()}-text");

            PreviewGenderText.Text = $"{species} | {sex} | {gender}";
        }
        else
        {
            PreviewGenderText.Text = Loc.GetString("arcane-detail-examinable-species-unknown");
        }

        TargetPreview.SetEntity(entity);
        TargetPreview.OverrideDirection = RotationSequence[_currentDirectionIndex];

        entityManager.TryGetComponent(entity, out CharacterDescriptionComponent? appearance);
        CharacterDescriptionComponent? character = null;
        if (mind.HasValue)
            entityManager.TryGetComponent(mind.Value, out character);

        SetDescription(PreviewAppearanceText, appearance?.Description, "arcane-detail-examinable-empty-appearance");
        SetDescription(PreviewCharacterText, character?.Description, "arcane-detail-examinable-empty-character");

        var characterInfoSystem = entityManager.System<SLSharedCharacterInfoSystem>();

        string? exploitableInfo = null;
        if (characterInfoSystem.CanAccessExploitableData(entity, viewer)
            && entityManager.TryGetComponent(entity, out ExploitableInfoComponent? exploitable))
        {
            exploitableInfo = exploitable.Info;
        }

        string? secrets = null;
        if (characterInfoSystem.CanAccessSecretData(entity, viewer)
            && entityManager.TryGetComponent(entity, out CharacterSecretsComponent? secretsComponent))
        {
            secrets = secretsComponent.Secrets;
        }

        ExploitableSection.Visible = !string.IsNullOrWhiteSpace(exploitableInfo);
        SecretsSection.Visible = !string.IsNullOrWhiteSpace(secrets);
        PreviewTabs.SetTabVisible(2, ExploitableSection.Visible || SecretsSection.Visible);
        SetDescription(PreviewExploitableText, exploitableInfo, "arcane-detail-examinable-empty-exploitable");
        SetDescription(PreviewSecretsText, secrets, "arcane-detail-examinable-empty-secrets");

        string? oocNotes = null;
        string? personalNotes = null;
        if (mind.HasValue)
        {
            if (entityManager.TryGetComponent(mind.Value, out RoleplayInfoComponent? roleplayInfo))
                oocNotes = roleplayInfo.OOCNotes;
            if (entityManager.TryGetComponent(mind.Value, out MindSecretsComponent? mindSecrets))
                personalNotes = mindSecrets.PersonalNotes;
        }

        SetDescription(PreviewOOCText, oocNotes, "arcane-detail-examinable-empty-ooc");
        PersonalNotesSection.Visible = !string.IsNullOrWhiteSpace(personalNotes);
        SetDescription(PreviewPersonalNotesText, personalNotes, "arcane-detail-examinable-empty-personal-notes");

        if (entityManager.TryGetComponent(entity, out CharacterImageComponent? imageComponent)
            && !string.IsNullOrEmpty(imageComponent.ImageUrl))
        {
            LoadCharacterImage(imageComponent.ImageUrl, entityManager);
        }
        else
        {
            ReleaseCharacterImage();
            CharacterImageSection.Visible = false;
        }
    }

    public void ClearCharacter()
    {
        TargetPreview.SetEntity(null);
        PreviewNameText.Text = string.Empty;
        PreviewGenderText.Text = string.Empty;

        PreviewAppearanceText.Text = null;
        PreviewCharacterText.Text = null;
        PreviewExploitableText.Text = null;
        PreviewSecretsText.Text = null;
        PreviewOOCText.Text = null;
        PreviewPersonalNotesText.Text = null;
        ReleaseCharacterImage();

        ExploitableSection.Visible = false;
        SecretsSection.Visible = false;
        PersonalNotesSection.Visible = false;
        PreviewTabs.SetTabVisible(2, false);
        CharacterImageSection.Visible = false;
    }

    private void RotateDirection(int step)
    {
        _currentDirectionIndex = (_currentDirectionIndex + step + RotationSequence.Length) % RotationSequence.Length;
        TargetPreview.OverrideDirection = RotationSequence[_currentDirectionIndex];
    }

    private static void SetDescription(RichTextLabel label, string? content, string emptyMessage)
    {
        var text = string.IsNullOrWhiteSpace(content)
            ? Loc.GetString(emptyMessage)
            : FormattedMessage.RemoveMarkupPermissive(content);

        label.SetMessage(text);
        label.InvalidateMeasure();
    }

    private void LoadCharacterImage(string imageUrl, IEntityManager entityManager)
    {
        ReleaseCharacterImage();
        CharacterImageSection.Visible = true;

        _characterImageRequestId = entityManager.System<RemoteImageSystem>().RequestImage(
            imageUrl,
            (texture, _) =>
            {
                _characterImageRequestId = 0;
                _characterImageTexture = texture;
                CharacterImage.Texture = texture;
            },
            _ =>
            {
                _characterImageRequestId = 0;
                CharacterImageSection.Visible = false;
            });
    }

    private void ReleaseCharacterImage()
    {
        var requestId = _characterImageRequestId;
        _characterImageRequestId = 0;
        if (requestId != 0
            && _entityManager.TrySystem<RemoteImageSystem>(out var remoteImageSystem))
        {
            remoteImageSystem.CancelRequest(requestId);
        }

        CharacterImage.Texture = null;
        _characterImageTexture?.Dispose();
        _characterImageTexture = null;
    }
}
